name: Deploy

on:
  push:
    branches:
    - stable
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: cloudflare/wrangler-action@1.2.0
      with:
        preCommands: cargo install worker-build
        apiToken: ${{ secrets.CF_API_TOKEN }}
        secrets: |
          DISCORD_TOKEN
          DISCORD_APPID
          DISCORD_PUBKEY
      env:
        DISCORD_TOKEN:  ${{ secrets.DISCORD_TOKEN  }}
        DISCORD_APPID:  ${{ secrets.DISCORD_APPID  }}
        DISCORD_PUBKEY: ${{ secrets.DISCORD_PUBKEY }}
