name: Deploy

on:
  push:
    branches:
    - stable
  repository_dispatch:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Deploy to Cloudflare"
      run: |
        cargo install wrangler worker-build
        wrangler publish
      env:
        CF_API_TOKEN:   ${{ secrets.CF_API_TOKEN }}
        DISCORD_TOKEN:  ${{ secrets.DISCORD_TOKEN  }}
        DISCORD_APPID:  ${{ secrets.DISCORD_APPID  }}
        DISCORD_PUBKEY: ${{ secrets.DISCORD_PUBKEY }}